### ISSUE TITLE
multiple lines do not work in facebook.js

### ISSUE THREAD

**Issue by tchen01** [tchen01/monospace#16]
the large chat treats more than 2 consecutive line breaks the same and so the original number of breaks cannot be determined. The small chat comes out correctly but that means the line numbers do not match. 

I do not see a way to tell how many linebreaks there should be without getting data from somewhere else.

If line numbers do not match then it might be confusing if they are used to talk about the code. I suggest making the small chat match with the large one.

**Comment by tchen01** [comment]
At the moment I have updated facebook.js to treat multiple line breaks as a double line break so that the code will be rendered the same in both places.

**Comment by jayelm** [comment]
So...done
